# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ECommerceApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ECommerceApp
  pod 'IQKeyboardManagerSwift'

  target 'ECommerceAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ECommerceAppUITests' do
    # Pods for testing
  end

end
